# Generated by Django 2.0.1 on 2020-04-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False, verbose_name='工单ID')),
                ('zc_type', models.CharField(max_length=100, verbose_name='资产状态')),
                ('zc_number', models.CharField(max_length=200, verbose_name='资产编号')),
                ('zc_name', models.CharField(max_length=200, verbose_name='资产名称')),
                ('zc_site', models.CharField(max_length=200, verbose_name='资产地点')),
                ('oa_id', models.CharField(max_length=200, verbose_name='OA请求ID')),
                ('reception_bill', models.ImageField(default='', upload_to='reception', verbose_name='接收单')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('tag', models.CharField(max_length=100, verbose_name='标签')),
                ('receive_name', models.CharField(max_length=100, verbose_name='领用人')),
                ('other_bill', models.ImageField(default='', upload_to='other', verbose_name='对方申请单')),
                ('state', models.CharField(default='启用', max_length=100, verbose_name='状态')),
                ('execute_user', models.CharField(max_length=100, verbose_name='操作人员')),
                ('pro1', models.CharField(max_length=200, verbose_name='属性1')),
                ('pro2', models.CharField(max_length=200, verbose_name='属性2')),
                ('pro3', models.CharField(blank=True, max_length=200, null=True, verbose_name='属性3')),
            ],
            options={
                'verbose_name_plural': '工单表',
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='用户密码')),
                ('authority', models.CharField(default='普通用户', max_length=1000, verbose_name='用户权限')),
                ('state', models.CharField(default='激活', max_length=20, verbose_name='用户状态')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZGG.User', verbose_name='操作人员'),
        ),
    ]
