# Generated by Django 2.0.1 on 2020-04-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZGG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='other_bill',
            field=models.ImageField(blank=True, null=True, upload_to='other', verbose_name='对方申请单'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='reception_bill',
            field=models.ImageField(blank=True, null=True, upload_to='reception', verbose_name='接收单'),
        ),
    ]
