# Generated by Django 2.0.1 on 2020-05-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZGG', '0002_auto_20200427_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authority',
        ),
        migrations.AddField(
            model_name='user',
            name='ltt_authority',
            field=models.CharField(default='普通用户', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='zgg_authority',
            field=models.CharField(default='普通用户', max_length=300),
        ),
    ]
