# Generated by Django 2.0.1 on 2020-05-06 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZGG', '0003_auto_20200506_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(default='权限', max_length=300)),
            ],
            options={
                'verbose_name_plural': '权限表',
                'db_table': 'authority',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='ltt_authority',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zgg_authority',
        ),
        migrations.AddField(
            model_name='user',
            name='ltt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ltt', to='ZGG.Authority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zgg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zgg', to='ZGG.Authority'),
            preserve_default=False,
        ),
    ]
