# Generated by Django 2.0.1 on 2020-05-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZGG', '0004_auto_20200506_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authority',
            old_name='authority',
            new_name='a_name',
        ),
    ]
