# Generated by Django 2.0.1 on 2020-04-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kind',
            },
        ),
        migrations.CreateModel(
            name='Ltt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=200)),
                ('pn_desc', models.CharField(max_length=1000)),
                ('put_time', models.CharField(max_length=200)),
                ('out_time', models.CharField(max_length=200)),
                ('execute_user', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=200)),
                ('over_time', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('log', models.TextField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='LTT.Class')),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kind', to='LTT.Kind')),
            ],
            options={
                'db_table': 'LTT',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='ltt',
            name='p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='LTT.Project'),
        ),
    ]
