# Generated by Django 2.0.1 on 2020-04-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTT', '0003_auto_20200422_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltt',
            name='ltt_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ltt',
            name='sn',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
