# Generated by Django 2.0.1 on 2020-04-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTT', '0004_auto_20200423_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltt',
            name='out_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ltt',
            name='over_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ltt',
            name='put_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ltt',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
