# Generated by Django 2.0.1 on 2020-04-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LTT', '0005_auto_20200427_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='c',
        ),
        migrations.AddField(
            model_name='ltt',
            name='c',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='LTT.Class'),
            preserve_default=False,
        ),
    ]
